### ISSUE TITLE
cue/cmd template is not expended in _tool.cue when the data is not in the leaf directory 

### ISSUE THREAD

**Issue by huangminghuang** [cuelang/cue#206]
The following code demonstrate the bug I have encountered.

```
$ cue mod init
$ cat << EOF > test.cue
package test

test: [ID=_]: {
  name: ID
}

test: A: {}
EOF

$ mkdir subdir
$ cat << EOF > subdir/test.cue
package test
EOF

$ cat <<EOF > dump_tool.cue
package test

import (
	"encoding/yaml"
	"tool/cli"
)

x: test
command: dump: {
	task: print: cli.Print & {
		text: yaml.Marshal(x)
	}
}
EOF

$ cue eval ./...
// /tmp/cuetest
test: {
    A: {
        name: "A"
    }
}

// /tmp/cuetest/dir
test: {
    A: {
        name: "A"
    }
}
```

```
$ cue dump ./...
A: {}
```

**Comment by mpvl** [comment]
This was related to one of your earlier bugs and is fixed in tip.

**Comment by huangminghuang** [comment]
I tried with the commit d100ae6ab4237695df9a839d789b7488e1f0ae11, the bug still exists.

**Comment by huangminghuang** [comment]
Just tried 0.15 version downloaded from homebrew, the bug still there. You only fix the problem with 'cue eval ./...' , but NOT for 'cue dump ./...'

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/206.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
